# Generated by Django 3.0.3 on 2020-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoint1_waypoint2', models.CharField(max_length=200)),
                ('distance_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waypoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=35)),
                ('district', models.CharField(max_length=35)),
            ],
        ),
    ]
