# Generated by Django 3.0.3 on 2020-04-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distance',
            options={'verbose_name_plural': 'Distance'},
        ),
        migrations.AlterModelOptions(
            name='waypoints',
            options={'verbose_name_plural': 'Waypoints'},
        ),
    ]
